// data.js (FULL + ACCURATE, includes Desert Wolf in MAGE)
const levelXP = [
  null,
  0, 46, 99, 159, 229, 309, 401, 507, 628, 768,
  928, 1112, 1324, 1567, 1847, 2168, 2537, 2961, 3448, 4008,
  4651, 5389, 6237, 7212, 8332, 9618, 11095, 12792, 14742, 16982,
  19555, 22510, 25905, 29805, 34285, 39431, 45342, 52132, 59932, 68892,
  79184, 91006, 104586, 120186, 138106, 158690, 182335, 209496, 240696, 276536,
  317705, 364996, 419319, 481720, 553400, 635738, 730320, 838966, 963768, 1107128,
  1271805, 1460969, 1678262, 1927866, 2214586, 2543940, 2922269, 3356855, 3856063, 4429503,
  5088212, 5844870, 6714042, 7712459, 8859339, 10176758, 11690075, 13428420, 15425254, 17719014,
  20353852, 23380486, 26857176, 30850844, 35438364, 40708040, 46761308, 53714688, 61702024, 70877064,
  81416417, 93522954, 107429714, 123404386, 141754466, 162833172, 187046247, 214859767, 246809111, 283509271,
  325666684, 374092835, 429719875, 493618564, 567018884, 651333710, 748186012, 859440093, 987237472, 1134038112,
  1302667765, 1496372370, 1718880532, 1974475291, 2268076571, 2605335878, 2992745089, 3437761413, 3948950932, 4536153492
];

const skills = {
  fishing: {
    title: "Fishing",
    currentLabel: "Your Fishing Level",
    targetLabel: "Target Fishing Level",
    selectHint: "Select a fish (locked until you reach the required level)",
    unitsLabel: (name) => `Total ${name}`,
    materialsMode: "simple",
    items: [
      { key:"anchovies",   name:"Anchovies",    level:1,   xp:10,    meta:{ bait:"Earthworm" } },
      { key:"goldfish",    name:"Goldfish",     level:5,   xp:20,    meta:{ bait:"Earthworm" } },
      { key:"mackerel",    name:"Mackerel",     level:10,  xp:50,    meta:{ bait:"Iceworm" } },
      { key:"squid",       name:"Squid",        level:20,  xp:115,   meta:{ bait:"Iceworm" } },
      { key:"sardine",     name:"Sardine",      level:30,  xp:375,   meta:{ bait:"Corpseworm" } },
      { key:"eel",         name:"Eel",          level:40,  xp:500,   meta:{ bait:"Toxic Worm" } },
      { key:"anglerfish",  name:"Anglerfish",   level:45,  xp:625,   meta:{ bait:"Sandworm" } },
      { key:"trout",       name:"Trout",        level:50,  xp:750,   meta:{ bait:"Beetle" } },
      { key:"jellyfish",   name:"Jellyfish",    level:55,  xp:900,   meta:{ bait:"Beetle" } },
      { key:"bass",        name:"Bass",         level:60,  xp:1350,  meta:{ bait:"Grasshopper" } },
      { key:"herringbone", name:"Herringbone",  level:65,  xp:1700,  meta:{ bait:"Grasshopper" } },
      { key:"tuna",        name:"Tuna",         level:70,  xp:2000,  meta:{ bait:"Wasp" } },
      { key:"lobster",     name:"Lobster",      level:75,  xp:3500,  meta:{ bait:"Scallop" } },
      { key:"sea_turtle",  name:"Sea Turtle",   level:80,  xp:6500,  meta:{ bait:"Scallop" } },
      { key:"manta_ray",   name:"Manta Ray",    level:85,  xp:9500,  meta:{ bait:"Crab" } },
      { key:"shark",       name:"Shark",        level:90,  xp:14500, meta:{ bait:"Bass" } },
      { key:"orca",        name:"Orca",         level:95,  xp:29500, meta:{ bait:"Bass" } },
      { key:"giant_squid", name:"Giant Squid",  level:100, xp:55000, meta:{ bait:"Bass" } },
    ]
  },

  mining: {
    title: "Mining",
    currentLabel: "Your Mining Level",
    targetLabel: "Target Mining Level",
    selectHint: "Select an ore (locked until you reach the required level)",
    unitsLabel: (name) => `Total ${name}`,
    materialsMode: "single",
    items: [
      { key:"tin",        name:"Tin Ore",        level:1,   xp:10,   meta:{ tool:"Pickaxe" } },
      { key:"copper",     name:"Copper Ore",     level:5,   xp:20,   meta:{ tool:"Pickaxe" } },
      { key:"iron",       name:"Iron Ore",       level:10,  xp:50,   meta:{ tool:"Pickaxe" } },
      { key:"coal",       name:"Coal Ore",       level:20,  xp:115,  meta:{ tool:"Pickaxe" } },
      { key:"silver",     name:"Silver Ore",     level:30,  xp:350,  meta:{ tool:"Pickaxe" } },
      { key:"crimsteel",  name:"Crimsteel Ore",  level:40,  xp:475,  meta:{ tool:"Pickaxe" } },
      { key:"gold",       name:"Gold Ore",       level:50,  xp:650,  meta:{ tool:"Pickaxe" } },
      { key:"mythan",     name:"Mythan Ore",     level:60,  xp:1200, meta:{ tool:"Pickaxe" } },
      { key:"cobalt",     name:"Cobalt Ore",     level:70,  xp:1800, meta:{ tool:"Pickaxe" } },
      { key:"varaxium",   name:"Varaxium",       level:75,  xp:3500, meta:{ tool:"Pickaxe" } },
      { key:"black_salt", name:"Black Salt",     level:80,  xp:5000, meta:{ tool:"Pickaxe" } },
      { key:"naturite",   name:"Naturite",       level:85,  xp:7250, meta:{ tool:"Pickaxe" } },
      { key:"obsidian",   name:"Obsidian",       level:90,  xp:9000, meta:{ tool:"Pickaxe" } },
    ]
  },

  woodcutting: {
    title: "Woodcutting",
    currentLabel: "Your Woodcutting Level",
    targetLabel: "Target Woodcutting Level",
    selectHint: "Select a log (locked until you reach the required level)",
    unitsLabel: (name) => `Total ${name}`,
    materialsMode: "single",
    items: [
      { key:"pine",      name:"Pine Logs",      level:1,  xp:10,    meta:{ tool:"Axe" } },
      { key:"dead",      name:"Dead Logs",      level:5,  xp:20,    meta:{ tool:"Axe" } },
      { key:"birch",     name:"Birch Logs",     level:10, xp:50,    meta:{ tool:"Axe" } },
      { key:"applewood", name:"Applewood",      level:20, xp:115,   meta:{ tool:"Axe" } },
      { key:"willow",    name:"Willow Logs",    level:30, xp:350,   meta:{ tool:"Axe" } },
      { key:"oak",       name:"Oak Logs",       level:40, xp:475,   meta:{ tool:"Axe" } },
      { key:"chestnut",  name:"Chestnut Logs",  level:50, xp:650,   meta:{ tool:"Axe" } },
      { key:"maple",     name:"Maple Logs",     level:60, xp:1200,  meta:{ tool:"Axe" } },
      { key:"olive",     name:"Olive Logs",     level:70, xp:1800,  meta:{ tool:"Axe" } },
      { key:"stinkwood", name:"Stinkwood",      level:75, xp:3500,  meta:{ tool:"Axe" } },
      { key:"magic",     name:"Magic Log",      level:80, xp:5000,  meta:{ tool:"Axe" } },
      { key:"palm",      name:"Palm Wood",      level:85, xp:7250,  meta:{ tool:"Axe" } },
      { key:"ironbark",  name:"Ironbark",       level:87, xp:8250,  meta:{ tool:"Axe" } },
      { key:"pearwood",  name:"Pearwood",       level:90, xp:9000,  meta:{ tool:"Axe" } },
      { key:"limewood",  name:"Lime Wood",      level:95, xp:14500, meta:{ tool:"Axe" } },
    ]
  },

  spellbinding: {
    title: "Spellbinding (Tailoring)",
    currentLabel: "Your Spellbinding Level",
    targetLabel: "Target Spellbinding Level",
    selectHint: "Select a craft (locked until you reach the required level)",
    unitsLabel: (name) => `Total ${name}`,
    materialsMode: "recipe",
    items: [
      { key:"paper",         name:"Paper",         level:1,  xp:1,    materials:[ {name:"Pine Logs", qty:1} ] },
      { key:"book",          name:"Book",          level:3,  xp:5,    materials:[ {name:"Paper", qty:5}, {name:"Leather", qty:1} ] },
      { key:"ember_tome",    name:"Ember Tome",    level:5,  xp:12,   materials:[ {name:"Book", qty:1}, {name:"Relic of Fire", qty:1}, {name:"Magic Essence", qty:1} ] },
      { key:"leech_tome",    name:"Leech Tome",    level:9,  xp:20,   materials:[ {name:"Book", qty:1}, {name:"Relic of Nature", qty:1}, {name:"Magic Essence", qty:1} ] },
      { key:"icicle_tome",   name:"Icicle Tome",   level:15, xp:28,   materials:[ {name:"Book", qty:1}, {name:"Ice Relic", qty:1}, {name:"Magic Essence", qty:1} ] },
      { key:"haunt_tome",    name:"Haunt Tome",    level:20, xp:40,   materials:[ {name:"Book", qty:1}, {name:"Cursed Relic", qty:1}, {name:"Magic Essence", qty:1} ] },
      { key:"ignite_tome",   name:"Ignite Tome",   level:29, xp:100,  materials:[ {name:"Book", qty:1}, {name:"Relic of Fire", qty:1}, {name:"Magic Essence", qty:5} ] },
      { key:"drain_tome",    name:"Drain Tome",    level:33, xp:115,  materials:[ {name:"Book", qty:1}, {name:"Relic of Nature", qty:1}, {name:"Magic Essence", qty:3} ] },
      { key:"freeze_tome",   name:"Freeze Tome",   level:40, xp:200,  materials:[ {name:"Book", qty:1}, {name:"Ice Relic", qty:1}, {name:"Magic Essence", qty:3} ] },
      { key:"curse_tome",    name:"Curse Tome",    level:60, xp:900,  materials:[ {name:"Book", qty:1}, {name:"Cursed Relic", qty:1}, {name:"Magic Essence", qty:3} ] },
      { key:"inferno_tome",  name:"Inferno Tome",  level:68, xp:1380, materials:[ {name:"Book", qty:1}, {name:"Relic of Fire", qty:1}, {name:"Magic Essence", qty:10} ] },
      { key:"consume_tome",  name:"Consume Tome",  level:76, xp:2110, materials:[ {name:"Book", qty:1}, {name:"Relic of Nature", qty:1}, {name:"Magic Essence", qty:6} ] },
      { key:"blizzard_tome", name:"Blizzard Tome", level:80, xp:2750, materials:[ {name:"Book", qty:1}, {name:"Ice Relic", qty:1}, {name:"Magic Essence", qty:6} ] },
      { key:"torture_tome",  name:"Torture Tome",  level:92, xp:4300, materials:[ {name:"Book", qty:1}, {name:"Cursed Relic", qty:1}, {name:"Magic Essence", qty:6} ] },
    ]
  },

  cooking: {
    title: "Cooking",
    currentLabel: "Your Cooking Level",
    targetLabel: "Target Cooking Level",
    selectHint: "Select a food (locked until you reach the required level)",
    unitsLabel: (name) => `Total ${name}`,
    materialsMode: "recipe",
    items: [
      { key:"cooked_anchovies",   name:"Cooked Anchovies",   level:1,   xp:10,    materials:[ {name:"Anchovies", qty:1} ] },
      { key:"cooked_mackerel",    name:"Cooked Mackerel",    level:10,  xp:50,    materials:[ {name:"Mackerel", qty:1} ] },
      { key:"cooked_squid",       name:"Cooked Squid",       level:20,  xp:115,   materials:[ {name:"Squid", qty:1} ] },
      { key:"cooked_sardine",     name:"Cooked Sardine",     level:30,  xp:375,   materials:[ {name:"Sardine", qty:1}, {name:"Salt", qty:1} ] },
      { key:"cooked_eel",         name:"Cooked Eel",         level:40,  xp:500,   materials:[ {name:"Eel", qty:2}, {name:"Salt", qty:1} ] },
      { key:"cooked_anglerfish",  name:"Cooked Anglerfish",  level:45,  xp:625,   materials:[ {name:"Anglerfish", qty:1}, {name:"Salt", qty:1} ] },
      { key:"cooked_trout",       name:"Cooked Trout",       level:50,  xp:750,   materials:[ {name:"Trout", qty:1}, {name:"Salt", qty:1} ] },
      { key:"bear_roast",         name:"Bear Roast",         level:55,  xp:1050,  materials:[ {name:"Bear Meat", qty:1}, {name:"Salt", qty:1} ] },
      { key:"polar_bear_roast",   name:"Polar Bear Roast",   level:65,  xp:1500,  materials:[ {name:"Polar Bear Meat", qty:1}, {name:"Pink Salt", qty:1} ] },
      { key:"cooked_bass",        name:"Cooked Bass",        level:60,  xp:1350,  materials:[ {name:"Bass", qty:1}, {name:"Pink Salt", qty:1} ] },
      { key:"cooked_tuna",        name:"Cooked Tuna",        level:70,  xp:2000,  materials:[ {name:"Tuna", qty:1}, {name:"Pink Salt", qty:1} ] },
      { key:"cooked_lobster",     name:"Cooked Lobster",     level:75,  xp:3500,  materials:[ {name:"Lobster", qty:1}, {name:"Pink Salt", qty:1} ] },
      { key:"cooked_sea_turtle",  name:"Cooked Sea Turtle",  level:80,  xp:6500,  materials:[ {name:"Sea Turtle", qty:1}, {name:"Pink Salt", qty:1} ] },
      { key:"cooked_manta_ray",   name:"Cooked Manta Ray",   level:85,  xp:9500,  materials:[ {name:"Manta Ray", qty:1}, {name:"Pink Salt", qty:1} ] },
      { key:"cooked_shark",       name:"Cooked Shark",       level:90,  xp:13500, materials:[ {name:"Shark", qty:1}, {name:"Black Salt", qty:1} ] },
      { key:"cooked_orca",        name:"Cooked Orca",        level:95,  xp:22500, materials:[ {name:"Orca", qty:1}, {name:"Black Salt", qty:1} ] },
      { key:"cooked_giant_squid", name:"Cooked Giant Squid", level:100, xp:41500, materials:[ {name:"Giant Squid", qty:1}, {name:"Black Salt", qty:1} ] },
    ]
  },

  crafting: {
    title: "Crafting",
    currentLabel: "Your Crafting Level",
    targetLabel: "Target Crafting Level",
    selectHint: "Select a relic (locked until you reach the required level)",
    unitsLabel: (name) => `Total ${name}`,
    materialsMode: "recipe",
    items: [
      { key:"relic_accuracy",    name:"Relic of Accuracy",    level:1,  xp:3,    materials:[ {name:"Pine Logs", qty:1} ] },
      { key:"relic_guarding",    name:"Relic of Guarding",    level:5,  xp:8,    materials:[ {name:"Dead Logs", qty:1} ] },
      { key:"relic_healing",     name:"Relic of Healing",     level:10, xp:18,   materials:[ {name:"Birch Logs", qty:1} ] },
      { key:"relic_wealth",      name:"Relic of Wealth",      level:20, xp:40,   materials:[ {name:"Applewood", qty:1} ] },
      { key:"relic_power",       name:"Relic of Power",       level:30, xp:105,  materials:[ {name:"Willow Logs", qty:1} ] },
      { key:"relic_nature",      name:"Relic of Nature",      level:40, xp:200,  materials:[ {name:"Oak Logs", qty:1} ] },
      { key:"relic_fire",        name:"Relic of Fire",        level:50, xp:425,  materials:[ {name:"Chestnut Logs", qty:1} ] },
      { key:"relic_damage",      name:"Relic of Damage",      level:60, xp:900,  materials:[ {name:"Maple Logs", qty:1} ] },
      { key:"relic_leeching",    name:"Relic of Leeching",    level:70, xp:1400, materials:[ {name:"Olive Logs", qty:1} ] },
      { key:"relic_experience",  name:"Relic of Experience",  level:75, xp:1850, materials:[ {name:"Maple Logs", qty:1}, {name:"Olive Logs", qty:1} ] },
      { key:"relic_wisdom",      name:"Relic of Wisdom",      level:77, xp:3600, materials:[ {name:"Stinkwood", qty:1}, {name:"Magic Log", qty:1} ] },
      { key:"ice_relic",         name:"Ice Relic",            level:80, xp:2750, materials:[ {name:"Magic Log", qty:1} ] },
      { key:"cursed_relic",      name:"Cursed Relic",         level:81, xp:3125, materials:[ {name:"Palm Wood", qty:1} ] },
      { key:"relic_efficiency",  name:"Relic of Efficiency",  level:85, xp:4250, materials:[ {name:"Pearwood", qty:1} ] },
      { key:"relic_unbroken",    name:"Relic of Unbroken",    level:87, xp:5000, materials:[ {name:"Ironbark", qty:1} ] },
      { key:"relic_affliction",  name:"Relic of Affliction",  level:90, xp:6000, materials:[ {name:"Lime Wood", qty:1}, {name:"Ancient Tablet", qty:1} ] },
    ]
  },

  alchemy: {
    title: "Alchemy",
    currentLabel: "Your Alchemy Level",
    targetLabel: "Target Alchemy Level",
    selectHint: "Select a plant (locked until you reach the required level)",
    unitsLabel: (name) => `Total ${name}`,
    materialsMode: "single",
    items: [
      { key:"brightrose",       name:"Brightrose",        level:1,   xp:1 },
      { key:"snowdrops",        name:"Snowdrops",         level:10,  xp:7 },
      { key:"dewberries",       name:"Dewberries",        level:20,  xp:43 },
      { key:"duskbell",         name:"Duskbell",          level:27,  xp:87 },
      { key:"dunethorn",        name:"Dunethorn",         level:35,  xp:120 },
      { key:"grimwood",         name:"Grimwood",          level:42,  xp:166 },
      { key:"dragons_whisker",  name:"Dragon's Whisker",  level:50,  xp:220 },
      { key:"grotwort",         name:"Grotwort",          level:56,  xp:313 },
      { key:"sunspore",         name:"Sunspore",          level:62,  xp:454 },
      { key:"moonshade",        name:"Moonshade",         level:68,  xp:577 },
      { key:"witchweave",       name:"Witchweave",        level:73,  xp:770 },
      { key:"voidberries",      name:"Voidberries",       level:77,  xp:1330 },
      { key:"drakewing",        name:"Drakewing",         level:81,  xp:2502 },
      { key:"dustwind",         name:"Dustwind",          level:85,  xp:4024 },
      { key:"stonesage",        name:"Stonesage",         level:91,  xp:5600 },
      { key:"dawnblossom",      name:"Dawnblossom",       level:96,  xp:9712 },
      { key:"frostweed",        name:"Frostweed",         level:100, xp:12275 },
    ]
  },

  melee: {
    title: "Melee",
    currentLabel: "Your Melee Level",
    targetLabel: "Target Melee Level",
    selectHint: "Select a monster (no requirements)",
    unitsLabel: () => `Total kills`,
    materialsMode: "kills",
    items: [
      { key:"ancient_bat",           name:"Ancient bat",           level:1, xp:2400,  meta:{ mobLevel:70 } },
      { key:"ancient_cyclops",       name:"Ancient cyclops",       level:1, xp:4000,  meta:{ mobLevel:90 } },
      { key:"anubis",               name:"Anubis",                level:1, xp:4000,  meta:{ mobLevel:90 } },
      { key:"anubis_elite",         name:"Anubis elite",          level:1, xp:7500,  meta:{ mobLevel:110 } },
      { key:"arosite_scarab",       name:"Arosite scarab",        level:1, xp:2850,  meta:{ mobLevel:75 } },
      { key:"baby_dragon",          name:"Baby dragon",           level:1, xp:5750,  meta:{ mobLevel:110 } },
      { key:"bat",                  name:"Bat",                  level:1, xp:8,     meta:{ mobLevel:1 } },
      { key:"brown_snake",          name:"Brown Snake",           level:1, xp:1000,  meta:{ mobLevel:120 } },
      { key:"cactus_soldier",       name:"Cactus soldier",        level:1, xp:2800,  meta:{ mobLevel:80 } },
      { key:"cave_bat",             name:"Cave bat",              level:1, xp:560,   meta:{ mobLevel:43 } },
      { key:"cave_spider",          name:"Cave spider",           level:1, xp:350,   meta:{ mobLevel:34 } },
      { key:"chicken",              name:"Chicken",              level:1, xp:10,    meta:{ mobLevel:1 } },
      { key:"corrupted_venomling",  name:"Corrupted Venomling",   level:1, xp:4150,  meta:{ mobLevel:92 } },
      { key:"defiled_scarab",       name:"Defiled Scarab",        level:1, xp:8000,  meta:{ mobLevel:105 } },
      { key:"desert_raptor",        name:"Desert raptor",         level:1, xp:1850,  meta:{ mobLevel:57 } },
      { key:"desert_wolf",          name:"Desert Wolf",           level:1, xp:13500, meta:{ mobLevel:140 } },
      { key:"disdained_venomling",  name:"Disdained Venomling",   level:1, xp:15000, meta:{ mobLevel:125 } },
      { key:"fishing_spider",       name:"Fishing Spider",        level:1, xp:38,    meta:{ mobLevel:8 } },
      { key:"forest_bat",           name:"Forest bat",            level:1, xp:60,    meta:{ mobLevel:15 } },
      { key:"forest_fiend",         name:"Forest fiend",          level:1, xp:1080,  meta:{ mobLevel:53 } },
      { key:"forest_spider",        name:"Forest Spider",         level:1, xp:55,    meta:{ mobLevel:12 } },
      { key:"gianthornet",          name:"Giant hornet",          level:1, xp:2100,  meta:{ mobLevel:62 } },
      { key:"golemite_bat",         name:"Golemite bat",          level:1, xp:4400,  meta:{ mobLevel:95 } },
      { key:"golemite_fiend",       name:"Golemite fiend",        level:1, xp:5270,  meta:{ mobLevel:100 } },
      { key:"gold_snake",           name:"Gold snake",            level:1, xp:1000,  meta:{ mobLevel:110 } },
      { key:"ice_fiend",            name:"Ice fiend",             level:1, xp:850,   meta:{ mobLevel:47 } },
      { key:"ice_raptor",           name:"Ice raptor",            level:1, xp:2750,  meta:{ mobLevel:73 } },
      { key:"ice_slime",            name:"Ice slime",             level:1, xp:165,   meta:{ mobLevel:21 } },
      { key:"ice_spider",           name:"Ice spider",            level:1, xp:250,   meta:{ mobLevel:28 } },
      { key:"juvenile_venomling",   name:"Juvenile Venomling",    level:1, xp:2300,  meta:{ mobLevel:65 } },
      { key:"luminant_slime",       name:"Luminant slime",        level:1, xp:2200,  meta:{ mobLevel:65 } },
      { key:"magnetite_scarab",     name:"Magnetite scarab",      level:1, xp:4250,  meta:{ mobLevel:90 } },
      { key:"mushroom",             name:"Mushroom",              level:1, xp:46,    meta:{ mobLevel:10 } },
      { key:"phantom_fiend",        name:"Phantom fiend",         level:1, xp:3600,  meta:{ mobLevel:88 } },
      { key:"phantom_flame",        name:"Phantom flame",         level:1, xp:2900,  meta:{ mobLevel:80 } },
      { key:"purple_snake",         name:"Purple Snake",          level:1, xp:900,   meta:{ mobLevel:135 } },
      { key:"rageful_venomling",    name:"Rageful Venomling",     level:1, xp:9500,  meta:{ mobLevel:110 } },
      { key:"raptor",               name:"Raptor",                level:1, xp:900,   meta:{ mobLevel:49 } },
      { key:"rock_fiend",           name:"Rock fiend",            level:1, xp:2000,  meta:{ mobLevel:60 } },
      { key:"ruby_scarab",          name:"Ruby scarab",           level:1, xp:1000,  meta:{ mobLevel:50 } },
      { key:"sandstone_golem",      name:"Sandstone Golem",       level:1, xp:11500, meta:{ mobLevel:150 } },
      { key:"sapphire_scarab",      name:"Sapphire scarab",       level:1, xp:400,   meta:{ mobLevel:40 } },
      { key:"scorpion",             name:"Scorpion",              level:1, xp:700,   meta:{ mobLevel:45 } },
      { key:"shadow_fiend",         name:"Shadow Fiend",          level:1, xp:1500,  meta:{ mobLevel:50 } },
      { key:"shadow_flame",         name:"Shadow flame",          level:1, xp:2800,  meta:{ mobLevel:78 } },
      { key:"skeletal_bat",         name:"Skeletal bat",          level:1, xp:385,   meta:{ mobLevel:35 } },
      { key:"skeletal_snake",       name:"Skeletal snake",        level:1, xp:300,   meta:{ mobLevel:30 } },
      { key:"slime",                name:"Slime",                 level:1, xp:16,    meta:{ mobLevel:4 } },
      { key:"snow_bat",             name:"Snow bat",              level:1, xp:125,   meta:{ mobLevel:18 } },
      { key:"snowman",              name:"Snowman",               level:1, xp:210,   meta:{ mobLevel:25 } },
      { key:"spectral_fiend",       name:"Spectral fiend",        level:1, xp:3100,  meta:{ mobLevel:85 } },
      { key:"spectral_flame",       name:"Spectral flame",        level:1, xp:2700,  meta:{ mobLevel:75 } },
      { key:"tormented_venomling",  name:"Tormented Venomling",   level:1, xp:7600,  meta:{ mobLevel:100 } },
    ]
  },

  mage: {
    title: "Mage",
    currentLabel: "Your Mage Level",
    targetLabel: "Target Mage Level",
    selectHint: "Select a monster (no requirements)",
    unitsLabel: () => `Total kills`,
    materialsMode: "kills",
    items: [
      { key:"ancient_bat",           name:"Ancient bat",           level:1, xp:2400,  meta:{ mobLevel:70 } },
      { key:"ancient_cyclops",       name:"Ancient cyclops",       level:1, xp:4000,  meta:{ mobLevel:90 } },
      { key:"anubis",               name:"Anubis",                level:1, xp:4000,  meta:{ mobLevel:90 } },
      { key:"anubis_elite",         name:"Anubis elite",          level:1, xp:7500,  meta:{ mobLevel:110 } },
      { key:"arosite_scarab",       name:"Arosite scarab",        level:1, xp:2850,  meta:{ mobLevel:75 } },
      { key:"baby_dragon",          name:"Baby dragon",           level:1, xp:5750,  meta:{ mobLevel:110 } },
      { key:"baby_seedling",        name:"Baby Seedling",         level:1, xp:40,    meta:{ mobLevel:10 } },
      { key:"bat",                  name:"Bat",                  level:1, xp:8,     meta:{ mobLevel:1 } },
      { key:"brown_snake",          name:"Brown Snake",           level:1, xp:1000,  meta:{ mobLevel:120 } },
      { key:"cactus_soldier",       name:"Cactus soldier",        level:1, xp:2800,  meta:{ mobLevel:80 } },
      { key:"cave_bat",             name:"Cave bat",              level:1, xp:560,   meta:{ mobLevel:43 } },
      { key:"cave_spider",          name:"Cave spider",           level:1, xp:350,   meta:{ mobLevel:34 } },
      { key:"chicken",              name:"Chicken",              level:1, xp:10,    meta:{ mobLevel:1 } },
      { key:"corrupted_venomling",  name:"Corrupted Venomling",   level:1, xp:4150,  meta:{ mobLevel:92 } },
      { key:"defiled_scarab",       name:"Defiled Scarab",        level:1, xp:8000,  meta:{ mobLevel:105 } },
      { key:"desert_raptor",        name:"Desert raptor",         level:1, xp:1850,  meta:{ mobLevel:57 } },

      // ✅ Added correctly: Desert Wolf (level 140) = 13500
      { key:"desert_wolf",          name:"Desert Wolf",           level:1, xp:13500, meta:{ mobLevel:140 } },

      { key:"disdained_venomling",  name:"Disdained Venomling",   level:1, xp:15000, meta:{ mobLevel:125 } },
      { key:"fishing_spider",       name:"Fishing Spider",        level:1, xp:38,    meta:{ mobLevel:8 } },
      { key:"forest_bat",           name:"Forest bat",            level:1, xp:60,    meta:{ mobLevel:15 } },
      { key:"forest_fiend",         name:"Forest fiend",          level:1, xp:1080,  meta:{ mobLevel:53 } },
      { key:"forest_spider",        name:"Forest Spider",         level:1, xp:55,    meta:{ mobLevel:12 } },
      { key:"gianthornet",          name:"Giant hornet",          level:1, xp:2100,  meta:{ mobLevel:62 } },
      { key:"golemite_bat",         name:"Golemite bat",          level:1, xp:4400,  meta:{ mobLevel:95 } },
      { key:"golemite_fiend",       name:"Golemite fiend",        level:1, xp:5270,  meta:{ mobLevel:100 } },
      { key:"gold_snake",           name:"Gold snake",            level:1, xp:1000,  meta:{ mobLevel:110 } },
      { key:"ice_fiend",            name:"Ice fiend",             level:1, xp:850,   meta:{ mobLevel:47 } },
      { key:"ice_raptor",           name:"Ice raptor",            level:1, xp:2750,  meta:{ mobLevel:73 } },
      { key:"ice_slime",            name:"Ice slime",             level:1, xp:165,   meta:{ mobLevel:21 } },
      { key:"ice_spider",           name:"Ice spider",            level:1, xp:250,   meta:{ mobLevel:28 } },
      { key:"juvenile_venomling",   name:"Juvenile Venomling",    level:1, xp:2300,  meta:{ mobLevel:65 } },
      { key:"luminant_slime",       name:"Luminant slime",        level:1, xp:2200,  meta:{ mobLevel:65 } },
      { key:"magnetite_scarab",     name:"Magnetite scarab",      level:1, xp:4250,  meta:{ mobLevel:90 } },
      { key:"mushroom",             name:"Mushroom",              level:1, xp:46,    meta:{ mobLevel:10 } },
      { key:"phantom_fiend",        name:"Phantom fiend",         level:1, xp:3600,  meta:{ mobLevel:88 } },
      { key:"phantom_flame",        name:"Phantom flame",         level:1, xp:2900,  meta:{ mobLevel:80 } },
      { key:"purple_snake",         name:"Purple Snake",          level:1, xp:900,   meta:{ mobLevel:135 } },
      { key:"rageful_venomling",    name:"Rageful Venomling",     level:1, xp:9500,  meta:{ mobLevel:110 } },
      { key:"raptor",               name:"Raptor",                level:1, xp:900,   meta:{ mobLevel:49 } },
      { key:"rock_fiend",           name:"Rock fiend",            level:1, xp:2000,  meta:{ mobLevel:60 } },
      { key:"ruby_scarab",          name:"Ruby scarab",           level:1, xp:1000,  meta:{ mobLevel:50 } },
      { key:"sapphire_scarab",      name:"Sapphire scarab",       level:1, xp:400,   meta:{ mobLevel:40 } },
      { key:"scorpion",             name:"Scorpion",              level:1, xp:700,   meta:{ mobLevel:45 } },
      { key:"seedling",             name:"Seedling",              level:1, xp:120,   meta:{ mobLevel:25 } },
      { key:"shadow_fiend",         name:"Shadow Fiend",          level:1, xp:1500,  meta:{ mobLevel:50 } },
      { key:"shadow_flame",         name:"Shadow flame",          level:1, xp:2800,  meta:{ mobLevel:78 } },
      { key:"skeletal_bat",         name:"Skeletal bat",          level:1, xp:385,   meta:{ mobLevel:35 } },
      { key:"skeletal_snake",       name:"Skeletal snake",        level:1, xp:300,   meta:{ mobLevel:30 } },
      { key:"slime",                name:"Slime",                 level:1, xp:16,    meta:{ mobLevel:4 } },
      { key:"snow_bat",             name:"Snow bat",              level:1, xp:125,   meta:{ mobLevel:18 } },
      { key:"snowman",              name:"Snowman",               level:1, xp:210,   meta:{ mobLevel:25 } },
      { key:"spectral_fiend",       name:"Spectral fiend",        level:1, xp:3100,  meta:{ mobLevel:85 } },
      { key:"spectral_flame",       name:"Spectral flame",        level:1, xp:2700,  meta:{ mobLevel:75 } },
      { key:"tormented_venomling",  name:"Tormented Venomling",   level:1, xp:7600,  meta:{ mobLevel:100 } },
    ]
  },
};
